### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by joshuavickstrom** [joshuavickstrom/TarotWebapp#1]
- [x]  Landing Page & spread prompt
- [x]  Spread options & layouts (with explanations)
- [x]  Moon phase calendar (with moon phase icon that updates)
- [x]  Card Details/Description Overlay

**Comment by mackbra** [comment]
## Basic Layout
![Image](https://github.com/joshuavickstrom/TarotWebapp/assets/44931601/750f8c71-a690-442c-9f30-8ab0b9725b71)

## Landing Page
![Image](https://github.com/joshuavickstrom/TarotWebapp/assets/44931601/0b4204f8-1df3-404d-add4-f5eab6358e17)
![Image](https://github.com/joshuavickstrom/TarotWebapp/assets/44931601/6cd0843e-d520-446d-b4e6-3e457c5cfceb)


## Tarot Spread
![Image](https://github.com/joshuavickstrom/TarotWebapp/assets/44931601/6161ad26-4ac4-4bf7-a978-41ca2787771e)

## Moon Phases Calendar & Overlay
![Image](https://github.com/joshuavickstrom/TarotWebapp/assets/44931601/79e708ef-0020-4026-8f5a-281e61cc1c58)
![Image](https://github.com/joshuavickstrom/TarotWebapp/assets/44931601/aca44c28-a0eb-465f-9b8d-b269de9ba668)

**Comment by LiliCecilia23** [comment]
![image](https://github.com/joshuavickstrom/TarotWebapp/assets/65939150/d3fbddb5-f35f-4f16-9573-e7cbec291f29)
![image](https://github.com/joshuavickstrom/TarotWebapp/assets/65939150/53e19edf-317a-4d63-bf89-01dae91fa3bb)
![image](https://github.com/joshuavickstrom/TarotWebapp/assets/65939150/9f1c5502-01f2-4173-a2c6-171c37354a4f)
