### ISSUE TITLE
JSON Compiling

### ISSUE THREAD

**Issue by joshuavickstrom** [joshuavickstrom/TarotWebapp#5]
Gather information on how compiling will work with JSON for project. 
If possible, setup JSON for compilation. 

_please add additional information_

- path of JSON file
- what gets compiled 
- anything else?

**Comment by joshuavickstrom** [comment]
esoteria/src/data/arcana.json
esoteria/src/data/moonPhases.json

**Comment by joshuavickstrom** [comment]
- [x] updates Moon Phase to include 'insightful intuitions'

**Comment by mackbra** [comment]
@LiliCecilia23 json summary:

ARCANA.JSON

arcana: [
  {  
        "arcana": (This is the card 'suit' ex. major arcana, The wands, The Cups, etc...)
        "card":  (Card Name ex: 'The Fool' or 'Eight of Cups')
        "brief":  (A one sentence summary about the card's meaning)
        "upright":  (A paragraph about the meaning on the card when in the upright position)
        "reverse":  (A paragraph about the card meaning when reversed)
        "advice":  (A paragraph about the card when in the advice position)
    },
}


MOONPHASES.JSON

moonPhases: [
            "phaseName": "New Moon",
            "phase": "primary",
            "title": "Seeding Intentions",
            "influence": (summary of moon phase influence on tarot pull)
]

moonMonths: [
            "month": "January",
            "moon": "Wolf Moon",
            "description": (blurb about the moon name history)
]

**Comment by mackbra** [comment]
@joshuavickstrom 
Sources:
https://www.tarot.com/
https://masteringthetarot.com/blog/tarot-and-lunar-phases/
https://www.timeanddate.com/moon/phases/
